USE [10.Oct_Data_25]
GO

SELECT [No#]
      ,[Date]
      ,[Customer Order Reference]
      ,[Customer Reference No#]
      ,[Customer]
      ,[Phone]
      ,[Mobile]
      ,[Operator(Created By)]
      ,[Pickupman]
      ,[Waybill No#]
      ,[From City]
      ,[Origin Branch]
      ,[To City]
      ,[Destination Branch]
      ,[Service Type]
      ,[Other]
      ,[Receiver Name]
      ,[Receiver Mobile]
      ,[Receiver Address]
      ,[Recipient Name]
      ,[Recipient Phone]
      ,[Payment By]
      ,[Payment Type]
      ,[Service]
      ,[Weight]
      ,[Express Income Amount]
      ,[COD Total Amount]
      ,[COD Express Income Amount]
      ,[COD Income Amount]
      ,[COD Payable Amount]
      ,[Sync Status]
  FROM [dbo].[OB_MDY]

GO


